version: "3.8"
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
        - MYSQL_ROOT_PASSWORD=
        - MYSQL_DATABASE=achatdb
    ports:
      - 3307:3306
    volumes:
      - db:/var/lib/mysql
  Achat-backend:
    depends_on:
      - mysqldb
    image: youssefelmili/project_achat_grp3:1.0.0
    restart: on-failure
    ports:
        - 8082:8082
    environment:
        SPRING_APPLICATION_JSON: '{ 
        
        “spring.datasource.url": "jdbc:mysql://localhost:3306/achatdb?createDatabasel fNotExist=true",
        “spring.datasource.username": "root",
        “spring. datasource.password": null,
        “spring. jpa.properties.hibernate.dialect": “org.hibernate.dialect.MySQL5InnoDBDialect",
        “spring.jpa.hibernate.ddl-auto": "update"
        }'

    stdin_open: true
    tty: true

volumes:
  db: