version: "3.8"
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    ports:
      - 3307:3306
    volumes:
      - db:/var/lib/mysql
  Achat-backend:
    depends_on:
      - mysqldb
    image: yassminezariat/achat:1.0.0
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root_password
    ports:
        - 8089:8089
    stdin_open: true
    tty: true
